### PR TITLE
Fixed display issue when the screen rotates

### PR DESCRIPTION
**Pull request by eisukekusachi**

### CODE REVIEW

**Review by waterbinbin — COMMENTED** [review]
I'll check the code first, and then I'll see if the logic can be added with rotation.

**Comment by eisukekusachi** [comment]
@waterbinbin 
I have made the corrections. Could you please build and verify whether it is working or not?

**Comment by waterbinbin** [comment]
我已收到你的邮件我会尽快回复你的！

**Comment by waterbinbin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you , I check it
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                153493486
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Eisuke ***@***.***>
            
        
      
      
        
         Date 
        
        
        07/2/2024 22:02
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [eisukekusachi/HandDrawingSwiftMetal] Fixed display issue when the screen rotates (PR #33)
        
      
    
  
  
@waterbinbin
I have made the corrections. Could you please build and verify whether it is working or not?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Pull request merged**
